org: rafaelportomoura
app: image-analysis
service: image-analysis

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - rekognition:DetectLabels
      Resource: '*'
    - Effect: 'Allow'
      Action:
        - translate:TranslateText
      Resource: '*'

functions:
  img-analysis:
    handler: handler.main
    events:
      - http:
          path: analysis
          method: get
